export const MenuItems = {
  Admin: [
    // { path: "/dashboard", title: "Dashboard", icon: "FiHome" },
    { path: "/home", title: "home", icon: "FiHome" },
    { path: "/users", title: "Users", icon: "FiUsers" },
    { path: "/questions", title: "Questions", icon: "FiHelpCircle" },
    { path: "/features", title: "Features", icon: "FiLayers" },
    { path: "/services", title: "Services", icon: "FiSettings" },
    { path: "/packages", title: "Packages", icon: "IoLogoFirebase" },
    { path: "/pricing", title: "Pricing", icon: "FiDollarSign" },
    { path: "/invoices", title: "Invoices", icon: "FaFileInvoice" },
  ],
  accountant: [{ path: "/invoices", title: "Invoices", icon: "FaFileInvoice" }],
};

export const allMenuItems = [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: "FaChartSimple",
    path: "/dashboard",
    roles: ["Admin", "manager"],
    withSub: false,
  },
  {
    id: "destinations",
    title: "Destinations",
    icon: "FaCity",
    path: "/destinations",
    roles: ["Admin", "manager"],
    withSub: true,
  },
  {
    id: "trips",
    title: "Trips",
    icon: "FaShip",
    path: "/trips",
    roles: ["Admin", "manager", "editor"],
    withSub: true,
  },
  {
    id: "facility",
    title: "Facility Setting",
    icon: "FaInfo",
    path: "/facility",
    roles: ["Admin", "manager", "sales"],
    withSub: false,
  },
];

export const SubMenuItems = [
  {
    id: "destinationsImgs",
    parentId: "destinations",
    title: "Images",
    icon: "FaFileImage",
    path: "/destinations/images",
    roles: ["Admin", "manager"],
  },
  {
    id: "tripsImgs",
    parentId: "trips",
    title: "Images",
    icon: "FaFileImage",
    path: "/trips/images",
    roles: ["Admin", "manager"],
  },
  {
    id: "tripsTrans",
    parentId: "trips",
    title: "Translations",
    icon: "FaGlobe",
    path: "/trips/translation",
    roles: ["Admin", "manager"],
  },
  {
    id: "prices",
    parentId: "trips",
    title: "Prices",
    icon: "FaDollarSign",
    path: "/trips/prices",
    roles: ["Admin", "manager"],
  },
  {
    id: "pickups",
    parentId: "trips",
    title: "Pick Ups",
    icon: "FaMapMarked",
    path: "/trips/pickups",
    roles: ["Admin", "manager"],
  },
  {
    id: "facility",
    parentId: "trips",
    title: "facility",
    icon: "FaInfo",
    path: "/trips/Facility",
    roles: ["Admin", "manager"],
  },
];
